// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/spellingbee/v1/spellingbee.proto

package spellingbeepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Letters       string                 `protobuf:"bytes,2,opt,name=letters,proto3" json:"letters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGameResponse) GetLetters() string {
	if x != nil {
		return x.Letters
	}
	return ""
}

type SubmitWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordRequest) Reset() {
	*x = SubmitWordRequest{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordRequest) ProtoMessage() {}

func (x *SubmitWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordRequest.ProtoReflect.Descriptor instead.
func (*SubmitWordRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type SubmitWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Letters       string                 `protobuf:"bytes,3,opt,name=letters,proto3" json:"letters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordResponse) Reset() {
	*x = SubmitWordResponse{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordResponse) ProtoMessage() {}

func (x *SubmitWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordResponse.ProtoReflect.Descriptor instead.
func (*SubmitWordResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitWordResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitWordResponse) GetLetters() string {
	if x != nil {
		return x.Letters
	}
	return ""
}

var File_api_spellingbee_v1_spellingbee_proto protoreflect.FileDescriptor

const file_api_spellingbee_v1_spellingbee_proto_rawDesc = "" +
	"\n" +
	"$api/spellingbee/v1/spellingbee.proto\x12\x0espellingbee.v1\"'\n" +
	"\x11CreateGameRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\">\n" +
	"\x12CreateGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aletters\x18\x02 \x01(\tR\aletters\"7\n" +
	"\x11SubmitWordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\"^\n" +
	"\x12SubmitWordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x18\n" +
	"\aletters\x18\x03 \x01(\tR\aletters2\xb7\x01\n" +
	"\vGameManager\x12S\n" +
	"\n" +
	"CreateGame\x12!.spellingbee.v1.CreateGameRequest\x1a\".spellingbee.v1.CreateGameResponse\x12S\n" +
	"\n" +
	"SubmitWord\x12!.spellingbee.v1.SubmitWordRequest\x1a\".spellingbee.v1.SubmitWordResponseB/Z-Assignmnet-1/api/spellingbee/v1;spellingbeepbb\x06proto3"

var (
	file_api_spellingbee_v1_spellingbee_proto_rawDescOnce sync.Once
	file_api_spellingbee_v1_spellingbee_proto_rawDescData []byte
)

func file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP() []byte {
	file_api_spellingbee_v1_spellingbee_proto_rawDescOnce.Do(func() {
		file_api_spellingbee_v1_spellingbee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_spellingbee_proto_rawDesc), len(file_api_spellingbee_v1_spellingbee_proto_rawDesc)))
	})
	return file_api_spellingbee_v1_spellingbee_proto_rawDescData
}

var file_api_spellingbee_v1_spellingbee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_spellingbee_v1_spellingbee_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: spellingbee.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 1: spellingbee.v1.CreateGameResponse
	(*SubmitWordRequest)(nil),  // 2: spellingbee.v1.SubmitWordRequest
	(*SubmitWordResponse)(nil), // 3: spellingbee.v1.SubmitWordResponse
}
var file_api_spellingbee_v1_spellingbee_proto_depIdxs = []int32{
	0, // 0: spellingbee.v1.GameManager.CreateGame:input_type -> spellingbee.v1.CreateGameRequest
	2, // 1: spellingbee.v1.GameManager.SubmitWord:input_type -> spellingbee.v1.SubmitWordRequest
	1, // 2: spellingbee.v1.GameManager.CreateGame:output_type -> spellingbee.v1.CreateGameResponse
	3, // 3: spellingbee.v1.GameManager.SubmitWord:output_type -> spellingbee.v1.SubmitWordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_spellingbee_v1_spellingbee_proto_init() }
func file_api_spellingbee_v1_spellingbee_proto_init() {
	if File_api_spellingbee_v1_spellingbee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_spellingbee_proto_rawDesc), len(file_api_spellingbee_v1_spellingbee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_spellingbee_v1_spellingbee_proto_goTypes,
		DependencyIndexes: file_api_spellingbee_v1_spellingbee_proto_depIdxs,
		MessageInfos:      file_api_spellingbee_v1_spellingbee_proto_msgTypes,
	}.Build()
	File_api_spellingbee_v1_spellingbee_proto = out.File
	file_api_spellingbee_v1_spellingbee_proto_goTypes = nil
	file_api_spellingbee_v1_spellingbee_proto_depIdxs = nil
}
