networks:
  appnet:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
#    environment:
#      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  spelling-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - STATS_PATH=/app/data/stats.json
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - appnet
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
    restart: unless-stopped

  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.socket
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - STATS_PATH=/app/data/stats.json
      - TCP_ADDR=:9000
    ports:
      - "9000:9000"
    networks:
      - appnet
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
      - spelling-server
    restart: unless-stopped

volumes:
  rabbitmq-data:
    driver: local
